---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-commander2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
      name: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
        name: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander
        env:
        - name: REDIS_HOST
          value: redis-enterprise-database
        - name: REDIS_PORT
          value: 15731
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redb-redis-enterprise-database
              key: password
        ports:
        - name: redis-commander
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: redis-commander
    name: redis-commander
  type: LoadBalancer
